### ISSUE TITLE
Can't load a big amount of IFC

### ISSUE THREAD

**Issue by MaxiMenace** [IFCjs/web-ifc-three#100]
Hello,

first sorry for my english, this is not my language.

Here is my problem : I have almost 4 giga of IFC Files to load (my PC has good configurations, RTX 3070 and 16 GB of RAM).
I built a function to load multiple IFC in a row (it work perfectly for almost 2 giga of IFC Files).
Once a certain amount of data has been loaded (i calculated almost 2.2 giga of files), it give me this error : 
![image](https://user-images.githubusercontent.com/104623771/165920163-01c74df1-5967-4aa3-b24e-9831659047a5.png)

In addition, i can't share here my IFC Files for personnal reasons.
Thanks in advance for your answers.

**Comment by agviegas** [comment]
Hey @MaxiMenace right now we are not able to support IFCs of that size. We will work on this in the future (probably next year), but right now this is out of IFC.js scope. Sorry for this! Feel free to bring this topic back in a year 🙂

**Comment by makc** [comment]
@MaxiMenace if you are feeling lucky, try to re-build wasm with higher MAXIMUM_MEMORY (which I think is around 2GB by default)
