### ISSUE TITLE
[documentation] codebase conflict in api hint

### ISSUE THREAD

**Issue by lewibs** [IFCjs/web-ifc-three#128]
ifc.getSpatialStructure(modelId, includeProperties)
model.getSpatialStructure(modelId)

when getSpatialStructure is called through the model it fails to maintain the 2nd parameter.
Upon reading the source code it is stated that use of this is depreciated so the bug is a non-issue. However, much of the documentation states that using the model directly is an option. 

as stated in https://ifcjs.github.io/info/docs/Guide/web-ifc-three/api
"Both IfcModel instances and IfcLoader.IfcManager can be used interchangeably to access the API. There's one difference: when using IfcModel, the ModelID never has to be given as an argument (it's known implicitly)."

This should be updated as the api through the model has been depreciated as seen here:
https://github.com/IFCjs/web-ifc-three/blob/main/web-ifc-three/src/IFC/components/IFCModel.ts

**Comment by aka-blackboots** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @aka-blackboots! Thanks for taking this bounty! The due date is May 5, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
::done

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::done

Hi, @aka-blackboots! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by aka-blackboots** [comment]
::expense::134265

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::134265

Hi, @aka-blackboots! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @aka-blackboots! Your [expense](https://opencollective.com/ifcjs/expenses/134265) has been approved!
