### ISSUE TITLE
Allow setItemVisibility to accept only expressId & modelId parameters

### ISSUE THREAD

**Issue by harrycollin** [IFCjs/web-ifc-three#13]
Setting element visibility could be improved by not requiring to pass geometry as an argument. Instead only passing expressId & modelId. This makes it easier to use when with UI integrations.

**Comment by antoniohof** [comment]
where did this method go?
I need to set item visibility passing only expressID.

Also need to get face indexes passing only expressID, do you know which function should I use now?

Thanks

**Comment by agviegas** [comment]
You can create geometric subsets (ergo changing the appearance of items) with [this](https://github.com/IFCjs/web-ifc-three/blob/daa1d992a12139dc3cd6f055920f8c54a2921638/src/IFC/Components/IFCManager.ts#L180). Documentation is on the way; in the meantime, you can look how we do it in the [example](https://github.com/IFCjs/web-ifc-three/blob/daa1d992a12139dc3cd6f055920f8c54a2921638/example/web-ifc-scene.js#L145). We are also refactoring that example to make it more clear. 

Thanks for your patience!

**Comment by antoniohof** [comment]
thank you very much @agviegas :)
