### ISSUE TITLE
Separate the floors

### ISSUE THREAD

**Issue by elias2089** [IFCjs/web-ifc-three#133]
Hello, I would like to know if in web-ifc-three, there is some way to separate the IFCBUILDINGSTOREY, at a configurable distance, something like this:
![split](https://user-images.githubusercontent.com/81208914/199550712-9a7913de-680d-45dc-8546-c6d5a4ba06c2.png)

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @aka-blackboots! Thanks for taking this bounty! The due date is December 19, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @aka-blackboots! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by antoniohof** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @antoniohof! Thanks for taking this bounty! The due date is March 2, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by antoniohof** [comment]
Dear elias2089,

I managed to do it like this:

`            this.model = this.IFCManager.scene.ifcModel
            this.spatialStructure = await this.IFCManager.scene.ifcModel.getSpatialStructure()

            // storeys are in this hierarchy
            const floors = this.spatialStructure.children[0].children[0].children
            
            const floor1ids = []
            floors[0].children.forEach((c)=> {
                floor1ids.push(c.expressID)
            })
   
            const floor2ids = []
            floors[1].children.forEach((c)=> {
                floor2ids.push(c.expressID)
            })

            // we don't want the subsets to appear directly into the scene, we first need to clone them, so pass a dummy object3d in the scene parameter
            const emptyObject = new Object3D()

            // create subset of first floor
            const floor1 = this.IFCManager.scene.ifcModel.ifcManager.subsets.createSubset({
                modelID: modelID,
                ids: floor1ids,
                material: null,
                scene: emptyObject,
                removePrevious: true,
            });

            // clone subset of first floor and add to threejs scene
            const floor1Mesh = new Mesh( floor1.geometry.clone(), floor1.material );
            this.IFCManager.scene.scene.add(floor1Mesh)

            // create subset of second floor
            const floor2 = this.IFCManager.scene.ifcModel.ifcManager.subsets.createSubset({
                modelID: modelID,
                ids: floor2ids,
                material: null,
                scene: emptyObject,
                removePrevious: true,
            });

            // clone subset of second floor and add to threejs scene
            const floor2Mesh = new Mesh( floor2.geometry.clone(), floor2.material );
            this.IFCManager.scene.scene.add(floor2Mesh)


            floor2Mesh.position.set(0,5,0)

            // remove original model's mesh
            this.IFCManager.scene.scene.remove(this.IFCManager.scene.originalModelMesh)

`


<img width="720" alt="image" src="https://user-images.githubusercontent.com/8311230/217964725-46a39641-1d4c-4428-9545-a160c206741f.png">

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/8311230/217965872-0aa26c8c-8f64-4527-8447-6482107580d2.png">


Let me know if that helps you,

If you want I can upload a demo with that.

All the best,

Antonio

**Comment by aka-blackboots** [comment]
@antoniohof The end goal over here would be integrate this as a functionality so that other user can directly use it as an API from web-ifc-three

**Comment by antoniohof** [comment]
I see! I'll try to do that soon and send a PR

**Comment by antoniohof** [comment]
ah wait, I found config.customID in createSubset. Then it's much easier.

**Comment by antoniohof** [comment]
``` 
this.spatialStructure = await this.IFCManager.scene.ifcModel.getSpatialStructure()

            // storeys are in this hierarchy
            const floors = this.spatialStructure.children[0].children[0].children
            
            const floor1ids = []
            floors[0].children.forEach((c)=> {
                floor1ids.push(c.expressID)
            })
   
            const floor2ids = []
            floors[1].children.forEach((c)=> {
                floor2ids.push(c.expressID)
            })

            // create subset of first floor
            const floor1 = this.IFCManager.scene.ifcModel.ifcManager.subsets.createSubset({
                modelID: modelID,
                ids: floor1ids,
                material: null,
                scene: this.IFCManager.scene.scene,
                removePrevious: false,
                customID: 'floor1'
            });

            // create subset of second floor
            const floor2 = this.IFCManager.scene.ifcModel.ifcManager.subsets.createSubset({
                modelID: modelID,
                ids: floor2ids,
                material: null,
                scene: this.IFCManager.scene.scene,
                removePrevious: false,
                customID: 'floor2'
            });

            floor2.position.set(0,5,0)

            // remove original model's mesh
            this.IFCManager.scene.scene.remove(this.IFCManager.scene.originalModelMesh)
```

**Comment by antoniohof** [comment]
What about a function in IFCManager.ts called "`createSubsetsOfType(config: TypeSubsetsConfig, IfcType : string)`"?

It can returns an array of the subsets of a specific ifcType. (e.g IFCBUILDINGSTOREY).

**Comment by elias2089** [comment]
Thank you very much @antoniohof , sorry for the delay, in the end I generated a subset for each BUILDINGSTORE and each one with its own customID, and then I used a gsap library that allows me to move the subsets with a transition of certain seconds, depending on the position of a slider. 
Slider:
![1](https://user-images.githubusercontent.com/81208914/218110093-66c09df3-8ccd-4b4a-a602-32deb5153765.png)
Ifc:
![2](https://user-images.githubusercontent.com/81208914/218110106-98ed6cc5-4968-43a1-93dc-ce49dcf00191.png)

Using gap, passing the slider position
timeline.to(subset.position, { duration: 0, y: position });

**Comment by antoniohof** [comment]
It's quite easy to do it with the current API, do we really need to have a separate method for this? @agviegas

**Comment by agviegas** [comment]
### 🔴🔴🔴

Hi, @antoniohof! The date is past due, your assignment has been revoked. It’s now available for anyone to take.

**Comment by agviegas** [comment]
@antoniohof you are right! I'm going to shut this down.
