### ISSUE TITLE
Implement UMD support

### ISSUE THREAD

**Issue by jespa007** [IFCjs/web-ifc-three#135]
Hi,

I have my javascript develop environment compatibles only with scripttag or Universal Module Definition (UMD) and, as far as I have tested, web-ifc-three.js generates library output for .js ES2015 Module.

I didn't saw any example how to build web-ifc-three library output for other types, so I supose the feature to generate web-ifc-three for UMD is not implemented yet. 

Following this article (https://adostes.medium.com/authoring-a-javascript-library-that-works-everywhere-using-rollup-f1b4b527b2a9) usign Rollup, every nnode project can be exported in:

- Universal Module Definition (UMD)
- ES2015 Module (ESM)
- CommonJS (CSJ)

I thing this issue is as easy as add a configuration in rollup.config

**Comment by jespa007** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @jespa007! Thanks for taking this bounty! The due date is February 6, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by jespa007** [comment]
[PR Submitted](https://github.com/IFCjs/web-ifc-three/pull/143)

**Comment by aka-blackboots** [comment]
> [PR Submitted](https://github.com/IFCjs/web-ifc-three/pull/143)

Merged 🚀

**Comment by jespa007** [comment]
@agviegas , the PR of this issue is already merged. So in principle this issue will be closed automatically, isn't it ?

**Comment by jespa007** [comment]
> > [PR Submitted](https://github.com/IFCjs/web-ifc-three/pull/143)
> 
> Merged 🚀

@aka-blackboots so this issue is already done ? I have to put ::done or is will close automatically ?

**Comment by agviegas** [comment]
::done

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::done

Hi, @jespa007! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by jespa007** [comment]
::expense::121503

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::121503

Hi, @jespa007! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @jespa007! Your [expense](https://opencollective.com/ifcjs/expenses/121503) has been approved!

**Comment by jespa007** [comment]
> ### 🟢🟢🟢
> Hi, @jespa007! Your [expense](https://opencollective.com/ifcjs/expenses/121503) has been approved!

thanks @agviegas , I hope I collaborate/fix with many other issues in the future :-)
