### ISSUE TITLE
Demo page not working: function import requires a callable

### ISSUE THREAD

**Issue by wwwouter** [IFCjs/web-ifc-three#156]
Tested https://ifcjs.github.io/web-ifc-three/example/ on Mac OSX with Chrome and Safari:

```
bundle.js:37339 wasm streaming compile failed: LinkError: WebAssembly.instantiate(): Import #49 module="a" function="X" error: function import requires a callable
```

Complete console output:

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/997207/222402985-4a0cbf33-bae6-4789-b433-f57fda24a7f7.png">

**Comment by makc** [comment]
the error says some func that wasm expects is not provided by js - this can be if wasm and js out of sync. but for me it works fine? so they either fixed it, or your browser cached something. try opening it in private window.

**Comment by wwwouter** [comment]
I tested it again and this specific error is gone.


Although I'm not able to load any .ifc file, because I'm getting different errors:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/997207/228323592-31968cfd-83ab-43d9-b001-50c49038bb19.png">

<img width="845" alt="image" src="https://user-images.githubusercontent.com/997207/228323651-7a90af2c-e75b-4390-bae7-3f7347cebefa.png">

**Comment by lyetjr** [comment]
Great, thanks

**Comment by DoisKoh** [comment]
> ![image](https://user-images.githubusercontent.com/35088509/228208453-47279aca-ce77-4283-b839-da611085d051.png)
> 
> windows & vue3
> 
> I don't know what I should do?

I have the same issue but I'm using Vite.

**Comment by protectione055** [comment]
I installed the same version of the dependency as the tutorial at the beginning and ran into the same problem. After updating the dependency to the latest version the problem was solved.

**Comment by tptspe** [comment]
I have same issue even though I updated all dependencies.
Here is my details https://github.com/emscripten-core/emscripten/issues/20119

Can you tell me what I am wrong?
Thanks
