### ISSUE TITLE
Mismatch web-ifc versions in example/package.json/web-ifc-three\package.json files

### ISSUE THREAD

**Issue by jespa007** [IFCjs/web-ifc-three#157]
Hi there,

Today as 2023/03/03 I've downloaded the code from github and there's a mismatch of web-ifc version in `example/package.json`/`web-ifc-three\package.json` files. In `web-ifc-three\package.json` refers web-ifc-0.0.39 whereas in `example\package.json` refers web-ifc-0.36.0

**Comment by agviegas** [comment]
Everything should be using version 0.0.39 now!
