### ISSUE TITLE
[Bug]: Error when trying to load a model

### ISSUE THREAD

**Issue by LeviSTA** [IFCjs/web-ifc-three#161]
When loading a large model in firefox, we receive this error and the file doesn't load:
![image](https://user-images.githubusercontent.com/123364333/228771425-dc3b3609-83c1-4a31-aeb1-8071fe43ca22.png)

Linked issue: https://github.com/IFCjs/web-ifc/issues/372

**Comment by agviegas** [comment]
This happens because this model is too large for web workers, so unfortunately you won't be able to use them with this.
