### ISSUE TITLE
IFCWorker.js.15776 report an error

### ISSUE THREAD

**Issue by Runasia** [IFCjs/web-ifc-three#167]
Hello
I had a bug in as mentioned above , it just like say i lack some wasm file or another some thing. but if i run it in browser.
it can arrive 
      console.log("here")
but can't array
     console.log("or here")
and what is magic word.. 

![image](https://github.com/IFCjs/web-ifc-three/assets/39799280/2d9bf3aa-4bb9-4038-ae1e-b833c13dd677)

`    ifc_init() {
      const ifc_loader = new IFCLoader()
      ifc_loader.ifcManager.setWasmPath("../wasm")
      // await ifc_loader.ifcManager.setWasmPath("/wasm/")
      ifc_loader.ifcManager.parser.setupOptionalCategories({
            [IFCSPACE]: false

          }
      )

      //npm i three-mesh-bvh或yarn add three-mesh-bvh
      ifc_loader.ifcManager.setupThreeMeshBVH(
          acceleratedRaycast,
          computeBoundsTree,
          disposeBoundsTree,
      );

      ifc_loader.ifcManager.setOnProgress(
          (event) => {
            const progress = (event.total / event.progress) * 100;
            console.log("Progress: ", progress, "%");

          }
      )

      ifc_loader.ifcManager.applyWebIfcConfig({
        COORDINATE_TO_ORIGIN: true,
        USE_FAST_BOOLS: false,
      });

       ifc_loader.ifcManager.useWebWorkers(
          true,
          "/ifc_worker/IFCWorker.js"
      );

     
      console.log("here")
      ifc_loader.load('/bimModel/rac_advanced_sample_project.ifc', function (model) {
        scene.add(model);
        console.log("or here")
        this.update_render()

      })

    },`

**Comment by Runasia** [comment]
![image](https://github.com/IFCjs/web-ifc-three/assets/39799280/81e5e805-3f6a-47e8-9e50-780ddeb7d10f)

Go ahead, it's say instantiateArrayBuffer has some..? please help me . Thinks!

**Comment by berry4u** [comment]
the same error I reported yesterday in issue #168

**Comment by Runasia** [comment]
I find that if i delete the 'await' behind of the ifc_loader.load() in my code , it can work ,so i think its maybe due to async mistake.

**Comment by Runasia** [comment]
I find that if i delete the 'await' behind of the ifc_loader.load() in my code , it can work ,so i think its maybe due to async mistake.  is not like   code  of my first up.
` async ifc_init() {
      const ifc_loader = new IFCLoader()
      await ifc_loader.ifcManager.setWasmPath("../wasm/")
      // await ifc_loader.ifcManager.setWasmPath("/wasm/")
      await ifc_loader.ifcManager.parser.setupOptionalCategories({
            [IFCSPACE]: false

          }
      )

    
 

      ifc_loader.ifcManager.setOnProgress(
          (event) => {
            const progress = (event.total / event.progress) * 100;
            console.log("Progress: ", progress, "%");

          }
      )


      await ifc_loader.ifcManager.applyWebIfcConfig({
        COORDINATE_TO_ORIGIN: true,
        USE_FAST_BOOLS: false,
      });

      // API 的其余部分保持不变，但所有的逻辑将发生在机器的另一个线程中，因此应用程序永远不会被繁重的操作所阻断。
      // await ifc_loader.ifcManager.useWebWorkers(
      //   true,
      //   "../assets/ifc_worker/IFCWorker.js"
      // );

      await ifc_loader.ifcManager.useWebWorkers(
          true,
          // "/ifc_worker/IFCWorker.js"
          "/ifc_worker/IFCWorker.js"
      );

      // src/assets/bimModel/rac_advanced_sample_project.ifc
      // ifc_loader.load('../assets/bimModel/rac_advanced_sample_project.ifc', function (model) {
      //   scene.add(model);
      //   this.update_render()
      //
      // })
      console.log("here")
      ifc_loader.load('/bimModel/RAC_basic_sample_project.ifc', function (model) {
        console.log("or here")
        scene.add(model);
        // this.update_render()
        renderer.render(scene, camera);


      })


    },
    update_render() {
      renderer.render(scene, camera);

    },
    add_controls() {
      const controls = new OrbitControls(camera, refDom);
      controls.addEventListener('change', this.update_render);

      window.addEventListener('resize', this.add_window_resize);
    },
    add_window_resize() {
      camera.aspect = window.innerWidth / window.innerHeight;
      camera.updateProjectionMatrix();
      renderer.setSize(window.innerWidth, window.innerHeight / 2);

      this.update_render()
    }


  },`
