### ISSUE TITLE
 Lifecycle script `build` failed with error:   Error: command failed  in workspace: web-ifc-three@0.0.125

### ISSUE THREAD

**Issue by Runasia** [IFCjs/web-ifc-three#170]
Hi, i am a new hand in web.
   I down load https://github.com/IFCjs/web-ifc-three and try to run it in local ,
as result  i do follow setps

1. run npm install web-ifc-three       (it likely default 0.0.125 ) 
2. run   "setup-repo": "npm i -g rollup && npm i -g cpy-cli",   (it's in  root directory )
3. run   "build": "cd ./web-ifc-three && npm run build && cd .. && cd ./example && npm run build", 

if i do until 3 ,i will get following ERR
`npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed
npm ERR!   in workspace: web-ifc-three@0.0.125
npm ERR!   at location: E:\code\threeifcofficialexaple\web-ifc-three\web-ifc-three
`

then i went to ../example/package.json  and run "build": "rollup -c && npm run copy-files",
it also has err
`npm ERR! Lifecycle script `copy-files` failed with error:
npm ERR! Error: command failed 
npm ERR!   in workspace: example@0.0.125
npm ERR!   at location: E:\code\threeifcofficialexaple\web-ifc-three\example
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed
npm ERR!   in workspace: example@0.0.125
npm ERR!   at location: E:\code\threeifcofficialexaple\web-ifc-three\example
` 

what can i do to running https://github.com/IFCjs/web-ifc-three  example .
If you see, thank you very much!!
If you can give me some advice,  thank you very very very much!!

**Comment by beachtom** [comment]
I am not sure what the issue is here it builds for me. Can you try download the live version from github and then running npm run setup-repo

**Comment by Runasia** [comment]
Just maybe version problem ，but need I finish the test preparation after repetition to try it again
