### ISSUE TITLE
Error loading IFC wasmModule.OpenModel is not a function

### ISSUE THREAD

**Issue by tentone** [IFCjs/web-ifc-three#173]
Hello

Im trying to load a IFC file using the library, i have setup the library alongside with three.js 0.152.0, web-ifc v0.0.41, web-ifc-three 
 v0.0.125.
 
 I tried rolling back  to three.js 0.149.0 but the problem persists
 
 I have copied the WASM files bundled with the library and set the WASM path to those files. When loading the file im getting the following error.

```IFCLoader.js:2650 TypeError: this.wasmModule.OpenModel is not a function
    at IfcAPI2.OpenModel (web-ifc-api.js:63155:34)
    at IFCParser.newIfcModel (IFCLoader.js:159:49)
    at IFCParser.parse (IFCLoader.js:139:16)
    at async IFCManager.parse (IFCLoader.js:2417:17)
    at async Object.eval [as onLoad] (IFCLoader.js:2645:16)
eval @ IFCLoader.js:2650
await in eval (async)
eval @ three.module.js:41908
Promise.then (async)
load @ three.module.js:41896
load @ IFCLoader.js:2640
App @ app.js:63
eval @ main.js:7
./src/main.js @ main.bundle.js:398
__webpack_require__ @ main.bundle.js:427
(anonymous) @ main.bundle.js:1507
(anonymous) @ main.bundle.js:1509
```

Here is the IFC file that im trying to load [EscritorioEQS.zip](https://github.com/IFCjs/web-ifc-three/files/11610842/EscritorioEQS.zip).

Thanks in advance

**Comment by nooralisysol** [comment]
can u show your code in file where that error showing
for me its loading perfectly
![image](https://github.com/IFCjs/web-ifc-three/assets/118829640/a890f34f-1485-4eb5-abab-6a27948638f5)

**Comment by greedyro** [comment]
same

**Comment by DJ-caddev** [comment]
We use web-ifc-three in a project, and both web-ifc's WASM version 0.0.40 and 0.0.41 have the `TypeError: this.wasmModule.OpenModel is not a function` issue.
WASM of web-ifc version 0.0.39 works fine.

**Comment by RyugaRyuzaki** [comment]
I guess you guys installed web-ifc-three first then you also installed web-ifc

**Comment by tentone** [comment]
> I guess you guys installed web-ifc-three first then you also installed web-ifc

There is no install/import order, getting it from npm and importing it as a module into code.

**Comment by Hamed-Abbasi** [comment]
I have the same issue
![image](https://github.com/IFCjs/web-ifc-three/assets/56730035/16fba618-9b5a-48a2-bad1-f929af4c1edc)

**Comment by bholathapa7** [comment]
> Hello
> 
> Im trying to load a IFC file using the library, i have setup the library alongside with three.js 0.152.0, web-ifc v0.0.41, web-ifc-three v0.0.125.
> 
> I tried rolling back to three.js 0.149.0 but the problem persists
> 
> I have copied the WASM files bundled with the library and set the WASM path to those files. When loading the file im getting the following error.
> 
> ```
>     at IfcAPI2.OpenModel (web-ifc-api.js:63155:34)
>     at IFCParser.newIfcModel (IFCLoader.js:159:49)
>     at IFCParser.parse (IFCLoader.js:139:16)
>     at async IFCManager.parse (IFCLoader.js:2417:17)
>     at async Object.eval [as onLoad] (IFCLoader.js:2645:16)
> eval @ IFCLoader.js:2650
> await in eval (async)
> eval @ three.module.js:41908
> Promise.then (async)
> load @ three.module.js:41896
> load @ IFCLoader.js:2640
> App @ app.js:63
> eval @ main.js:7
> ./src/main.js @ main.bundle.js:398
> __webpack_require__ @ main.bundle.js:427
> (anonymous) @ main.bundle.js:1507
> (anonymous) @ main.bundle.js:1509
> ```
> 
> Here is the IFC file that im trying to load [EscritorioEQS.zip](https://github.com/IFCjs/web-ifc-three/files/11610842/EscritorioEQS.zip).
> 
> Thanks in advance

The solution to this problem is to copy WASM files from the web-ifc-three to your root project and setWasmpath to that directory.  DO NOT COPY THE WASM FILE FROM OTHER PACKAGES LIKE web-ifc.
ifcLoader.ifcManager.setWasmPath("../../");

**Comment by Hamed-Abbasi** [comment]
Dear @bholathapa7 
As far as I know, there is no *.wasm file inside the web-ifc-three package, they are inside web-ifc.
Even in the documentation of the web-ifc-three, it's mentioned to copy them from web-ifc:
https://ifcjs.github.io/info/docs/Guide/web-ifc-three/api/#setwasmpath

**Comment by tentone** [comment]
To fix the problem i have removed "web-ifc" from the package.json.

"web-ifc-three" seems to be only compatible with older versions of the "web-ifc" project, so the WASM file from the last version is not compatible.
