### ISSUE TITLE
Missing esformatter as devDependency in order to be able to build dist

### ISSUE THREAD

**Issue by eng-luciano-julien** [IFCjs/web-ifc-three#20]
Missing esformatter as devDependency in package.json in order to be able to build dist folder.

**Comment by agviegas** [comment]
Hey, that's strange. I'm able to clone and build the dist without esformatter installed 🤔 Anyway, if in you end it's a requirement, feel free to open a PR and add it!

**Comment by vegarringdal** [comment]
@agviegas 

Maybe you have it installed globally ?
Should be added to devDep..

**Comment by agviegas** [comment]
Done!
