### ISSUE TITLE
Position and quaternion of IFC model do not reflect matrix values

### ISSUE THREAD

**Issue by xawill** [IFCjs/web-ifc-three#22]
Hi!

And thank you for this awesome library.

I just have an issue when loading a model. When I traverse the children Meshes, the position and the quaternion are always all zeros, even though the position and the rotation of the object is not zero in the Matrix of the Mesh. Is it intended ? If yes, can you explain me why ? If not, I guess a fix is just doing the following before returning the loaded model in `load`:

```
loadedModel.traverse((child) => {
  child.matrix.decompose(child.position, child.quaternion, child.scale);
});
```

I cannot upload the model I tested with (the .ifc file format is not supported), but you can download it [here](https://ifcwiki.org/images/e/e3/AC20-FZK-Haus.ifc).

~~Also, it looks like the world transform of the children Meshes is already baked in the geometry of the corresponding child Mesh, right ?~~ Actually I was wrong, it doesn't. Apparently the issue was coming from three.js not perfect support of the interleaved buffer attribute you use for your geometries.

**Comment by agviegas** [comment]
Hey @xawill what do you mean by "children meshes"? In theory, each model should only generate one mesh. We work with merged geometries to be able to support bigger models, and the intention is to allow users to traverse this with the API we are building on top of the `ifcLoader` object.

**Comment by xawill** [comment]
Thank you for checking the issue @agviegas. What you describe sounds to me like a perfect plan. Unfortunately, this is not the behaviour I experienced until now. You can replicate it very easily with the three.js editor: load an ifc file (for instance [this one](http://openifcmodel.cs.auckland.ac.nz/_models/20210125Prova.ifc)) and check the objects hierarchy on the right pane. There are hundreds of Meshes.

But it might be possible that what you describe is not actually released in three.js which is on r129. I noticed that on the model I linked above, there are pipes inside the house which are not correctly modelled by the IFCLoader shipped in the three.js editor, but when I load the model on your editor it renders correctly. So I guess your recent changes greatly improved the parsing of some IFC properties.

So maybe I created an issue which is not existing anymore ? I opened the issue here because I know this is the parent repository of the IFCLoader in three.js. I didn't test the issue with the current version of this repository. So maybe you already fixed it.

**Comment by agviegas** [comment]
You are totally right, and this offset between Three.js and IFC.js versions is something we'll have to live with for some time. We release new things every day / week, whereas Three.js has its own updating pace. What I'd suggest you if you want to work with the latest version is to import web-ifc-three (which is exactly the IFCLoader) and use it like the IFCLoader!

**Comment by xawill** [comment]
Okey, thank you for the suggestion. I guess we can then close the issue.
