### ISSUE TITLE
Translating/Rotating/Scaling the IFC causes the element picked (material) to appear in the original position

### ISSUE THREAD

**Issue by KiWiGiW** [IFCjs/web-ifc-three#29]
![image](https://user-images.githubusercontent.com/30846915/127120951-c326ca12-69db-45ee-a7f1-7dd67327565e.png)

**Comment by favreau84** [comment]
I went through the same issue. After loading the model, I start by centering the geometry of the model with a camera targeting 0,0,0. 
`const mesh = ifcModel.mesh;`
  `mesh.geometry.center();`
But doing so, the selected elements are kept in their original position (following the picking tutorial).

<img width="459" alt="Capture d’écran 2021-07-27 à 19 02 21" src="https://user-images.githubusercontent.com/18169247/127197658-c773247e-705e-46bf-806f-9c05609c84cb.png">

#### Proposition
One solution would be to add options in the model loader function, with a global transformation matrix to apply to the original mode.

**Comment by agviegas** [comment]
Solved! Try passing the IfcModel mesh in the `scene` parameter when creating a new subset and the subset will be a child of that mesh (thus reflecting the transformations you apply on it).
