### ISSUE TITLE
Tutorial update request

### ISSUE THREAD

**Issue by CrossStyle** [IFCjs/web-ifc-three#32]
Hello!

As I asked before in the discord, I hope you can update the documentation with tutorials on how to extract geometric information (e.g. position, width, length and height) and semantic information (e.g. material and storey).

I would be very grateful for this!

**Comment by agviegas** [comment]
[Here](https://ifcjs.github.io/info/docs/Guide/web-ifc-three/Tutorials/Properties) you have it!

**Comment by agviegas** [comment]
Just for clarification:
- geometric information should be found as QuantitySets, 
- material information can be found using [getMaterialsProperties()](https://ifcjs.github.io/info/docs/Guide/web-ifc-three/api#getmaterialsproperties).
- Due to the structure of IFC, for the storey right now you have to get the [spatial tree](https://ifcjs.github.io/info/docs/Guide/web-ifc-three/api#getspatialstructure) and check where is the ID of the element in question.

**Comment by CrossStyle** [comment]
@agviegas Wonderful work and thanks for your reply! However, I got the error when using the function getMaterialsProperties().
```
bundle.js:124995 Uncaught TypeError: manager.getMaterialsProperties is not a function
at HTMLCanvasElement.pick (bundle.js:124995)
```
The code I use is shown below.
```
function pick(event) {
  const found = cast(event)[0];
  if (found) {
    const foundModelID = found.object.modelID;
    console.log(found.object);
    const index = found.faceIndex;
    const geometry = found.object.geometry;
    // console.log(geometry);
    const manager = ifcLoader.ifcManager;
    const id = manager.getExpressId(geometry, index);
    // console.log(id);
    const type = manager.getIfcType(foundModelID, id);
    // console.log(type);
    const props = manager.getItemProperties(foundModelID, id, true);
    // output.innerHTML = JSON.stringify(props, null, 2);
    console.log(props);
    // console.log(props.GlobalId.value);
    const typeProps = manager.getTypeProperties(foundModelID, id, false);
    console.log(typeProps);

    const material = manager.getMaterialsProperties(foundModelID, id, false);
    console.log(material);

  }
}
```

**Comment by agviegas** [comment]
Have you tried updating to the last version?

**Comment by CrossStyle** [comment]
@agviegas It worked! Many thanks.
