### ISSUE TITLE
Can not read property index of undefined

### ISSUE THREAD

**Issue by SpiderProjectDeveloper** [IFCjs/web-ifc-three#40]
Hello! When loading a model (http://openifcmodel.cs.auckland.ac.nz/_models/23111022_IFCR2_Buildings_1.ifc), I received an error in developer's console window:
![error-message](https://user-images.githubusercontent.com/79970639/131041242-6f624878-725d-422f-bcc6-6c2d3b3d3637.png)
.

**Comment by Vladres** [comment]
Did you resolve it?

> Hello! When loading a model (http://openifcmodel.cs.auckland.ac.nz/_models/23111022_IFCR2_Buildings_1.ifc), I received an error in developer's console window:
> ![error-message](https://user-images.githubusercontent.com/79970639/131041242-6f624878-725d-422f-bcc6-6c2d3b3d3637.png)
> .

**Comment by agviegas** [comment]
Hey, sorry, I went on vacation and missed this. I'll take a look these days!

**Comment by Vladres** [comment]
> Hey, sorry, I went on vacation and missed this. I'll take a look these days!

Can you help with export? 
I generated mesh by threejs and i need to export in IFC format. Do you know, mb, can i do that?

**Comment by agviegas** [comment]
@Vladres sure. In the future, please try to keep the conversation of each issue inside that thread.
