### ISSUE TITLE
IFC export

### ISSUE THREAD

**Issue by Vladres** [IFCjs/web-ifc-three#47]
I need to export generated Mesh from threejs to IFC file format. How i can do that?

**Comment by Vladres** [comment]
this.wasmModule => undefined

ExportFileAsIFC(modelID) {
    console.log(this.wasmModule)
    this.wasmModule && this.wasmModule.ExportFileAsIFC(modelID);
    let result = this.fs.readFile("/export.ifc");
    this.wasmModule["FS_unlink"]("/export.ifc");
    return result;
  }

**Comment by agviegas** [comment]
Hey, right now the API for exporting is very raw. This means that exporting geometry is not automated at all, and requires a deep understanding of IFC. The plan is to develop that part of the API as soon as we can, although we are not there yet. The only solution I can come up with right now is using other libraries like IfcOpenShell or XBim and translate the geometry you have created!

**Comment by Vladres** [comment]
> Hey, right now the API for exporting is very raw. This means that exporting geometry is not automated at all, and requires a deep understanding of IFC. The plan is to develop that part of the API as soon as we can, although we are not there yet. The only solution I can come up with right now is using other libraries like IfcOpenShell or XBim and translate the geometry you have created!

Thanks)

**Comment by stijn-de-witte** [comment]
Hey,

Do you have an update on the timing of this feature?
It would be a great feature.

Thanks

**Comment by Nic-77** [comment]
Hey,
could someone give me a small example how to export a simple wall (described with length, height and thickness)?
I want to learn how to create or to fill up a simple IFC file.
For the first step i only need a small example or an explanation of the steps i have to do to create a really simple IFC file.
Please!
@agviegas 

I would also like to create tutorials for these simple steps for other users which have same questions as me...

Thanks in advance!
Best regards,
Nico

**Comment by Nic-77** [comment]
@Vladres @stijn-de-witte 

I don't know whether you found this:
[https://github.com/IFCjs/web-ifc/issues/127](https://github.com/IFCjs/web-ifc/issues/127)

For me it's very helpful.
Perhaps for you too?!

Br,
Nic

**Comment by agviegas** [comment]
Hi, we will work on [this](https://github.com/IFCjs/web-ifc-exporter) extensively next year!

**Comment by Nic-77** [comment]
Hi @agviegas,
thx for your feedback!
I'm looking forward to it!

Br,
Nic
