### ISSUE TITLE
U-Shape beam without representation in the model

### ISSUE THREAD

**Issue by RiaAguApo** [IFCjs/web-ifc-three#51]
No representation in the model of the U beam of this IFC file.
[C200.zip](https://github.com/IFCjs/web-ifc-three/files/7252135/C200.zip)

**Comment by agviegas** [comment]
Sorry for the delay! 💛 I solved this today. This should be working in the next web-ifc release. I haven't implemented the rounded bevels yet, but we'll improve that in the future.
