### ISSUE TITLE
Path to web-ifc.wasm file

### ISSUE THREAD

**Issue by vascoguita** [IFCjs/web-ifc-three#56]
To implement a Vue.js component that loads IFC files the path to web-ifc.wasm has to be specified with `setWasmPath(./foo/bar/)`.
The problem is that this method prefixes the specified path and doesn't accept an absolute path or a URL.
Would it be possible to provide more functions to set the wasm path?

In my case, if I set the path to the web-ifc.wasm file with `ifcLoader.ifcManager.setWasmPath("./")` my web app will perform a GET request to https://localhost:9200/home/vasco/Desktop/cernbox/web/node_modules/web-ifc/web-ifc.wasm, which results in a 404.
Since I have the web-ifc.wasm in the root of my build directory, I have to set the path to the web-ifc.wasm with `ifcLoader.ifcManager.setWasmPath("../../../../../../../")`. This way the web app performs a GET request to https://localhost:9200/web-ifc.wasm and everything works fine.
The problem here is that for different deployment environments the relative path will be different.
A method to set the wasm path with a URL or an absolute path would solve this problem.

**Comment by huzhy2019** [comment]
****

**Comment by agviegas** [comment]
Sorry for the delay, it has been busy weeks! 🔥 I solved this today. This should be working in the next web-ifc release. Let us know if that still doesn't work after that 😊
