### ISSUE TITLE
the npm package points to a index.js that doesn't exist

### ISSUE THREAD

**Issue by drcmda** [IFCjs/web-ifc-three#57]
docs state that ifc should be used as:

```jsx
import { IfcLoader } from 'web-ifc-three';
```

<img width="1021" alt="Screenshot 2021-10-29 at 14 00 59" src="https://user-images.githubusercontent.com/2223602/139430793-1ea8a509-06a0-447b-b891-f9f29fd8461a.png">

but that won't work, see https://unpkg.com/browse/web-ifc-three@0.0.75/ package.json says `"main": "index.js",` but there is none in the package.

**Comment by agviegas** [comment]
Hi! Did you try  ` import { IFCLoader } from "web-ifc-three/IFCLoader";`? We'll update the npm description, sorry for the inconvenience! 

![image](https://user-images.githubusercontent.com/56475338/139594275-5f7cb7f6-149e-4e08-93a0-74e5d41b6dac.png)

**Comment by agviegas** [comment]
Solved from `0.0.104`! 🎈 Sorry for the delay, these have been really busy weeks. Thanks for reporting this.
