### ISSUE TITLE
A model that used to be loaded correctly is now not being loaded with the last release

### ISSUE THREAD

**Issue by favreau84** [IFCjs/web-ifc-three#60]
I recently upgraded the lib to the new versions : 

 "web-ifc":"^0.0.24"=>  "^0.0.28",
  "web-ifc-three": "^0.0.68" => "^0.0.80",

Now, I have some models that are not loaded, (but they did load before),  like this one [station_0.ifc.zip](https://github.com/tomvandig/web-ifc/files/7493293/station_0.ifc.zip)

Any idea ?
Thanks !

**Comment by tomvandig** [comment]
I’ve done a bunch of changes to the bool algo, looks like I’m not done yet :-)

I will let you know when it’s fixed

**Comment by favreau84** [comment]
Hi @tomvandig, as @agviegas suggested, I turned the USE_FAST_BOOLS to true and this works. It's a little bit too magical but it does the job :-)

![image](https://user-images.githubusercontent.com/18169247/140795716-0b0f8cb8-dd23-4ef7-b75e-79c8ddbb54e8.png)
