### ISSUE TITLE
Values with accents and other symbols in IFC and UTF decoding

### ISSUE THREAD

**Issue by ElmoreaBIM** [IFCjs/web-ifc-three#61]
Hi, I have characters with accents in the IFC file, and when I read the value in the IFC it appears encoded as UTF-16 I think and I can't decode it.
Sorry for the wording of the question, I had to use automatic translator.
Thanks!

**Comment by tomvandig** [comment]
https://github.com/tomvandig/web-ifc/issues/58

**Comment by ElmoreaBIM** [comment]
Thanks @tomvandig , I will read it carefully

**Comment by agviegas** [comment]
Thanks @tomvandig !
