### ISSUE TITLE
Web-workers bug

### ISSUE THREAD

**Issue by KiWiGiW** [IFCjs/web-ifc-three#62]
useWebWorkers only works if it appears before the setWasmPath, otherwise it displays an error.

setWasmPath before useWebWorkers:
![image](https://user-images.githubusercontent.com/30846915/140743535-0b0b0e90-6ce7-454f-8bd9-aca4e107ddba.png)
![image](https://user-images.githubusercontent.com/30846915/140743218-739fc4ca-8e8a-426f-9b45-25d3a8254705.png)

useWebWorkers before setWasmPath:
![image](https://user-images.githubusercontent.com/30846915/140743468-212245f5-58a1-4c95-9367-55cfe0b732cc.png)
![image](https://user-images.githubusercontent.com/30846915/140743379-612111bb-3f8e-4a8c-b57e-d4bba76650ed.png)

**Comment by agviegas** [comment]
Solved from `0.0.106` 😊
