### ISSUE TITLE
Error with getPropertySets

### ISSUE THREAD

**Issue by TristanLecallier** [IFCjs/web-ifc-three#66]
Hi
I have on error when I try to get propertySets of elements. I don't think the problem is in my code because it works with other ifc files (and I also tried with the web-ifc-three github example with the same result...). 
I'm also not sure that the problem comes from the ifc file because I have no issues with other viewers... 
@agviegas I sent you the file privately
Thanks !
![image](https://user-images.githubusercontent.com/46968115/142574760-7d05a8b5-24f8-439c-9dcc-03fd148a76ae.png)

**Comment by agviegas** [comment]
Solved from `0.0.104`! 🔥 The cause of this issue was that some property sets had broken links. We are now warning that in the console but the execution proceeds and you can get the rest of the properties.
