### ISSUE TITLE
getIfcType is broken

### ISSUE THREAD

**Issue by antoniohof** [IFCjs/web-ifc-three#68]
After the latest release, when getting the structure of the IFC the type value is undefined.
And also the function getIfcType returns undefined.

<img width="277" alt="Screen Shot 2021-11-22 at 11 10 04" src="https://user-images.githubusercontent.com/8311230/142842787-0b281f3b-6e39-43df-8080-0f8e029fad63.png">

I suggest reverting this PR
https://github.com/IFCjs/web-ifc-three/commit/d71f893ba293ee546b0c43c66b427b0af6f25df8

**Comment by harrycollin** [comment]
@antoniohof I'm sorry you're having problems with this. I've tested this and can't reproduce the problem you're having. Can you give more details on your setup? FYI - I've tested getIfcType and getSpatialStructure, both return types as strings. 
![image](https://user-images.githubusercontent.com/10602138/142844880-834cb1c9-0c61-47e6-9242-577b8dbd869f.png)

**Comment by harrycollin** [comment]
My bad, I was testing in the wrong branch. Indeed getIfcType seems to be broken. But it seems to be broken after that commit. Perhaps @agviegas knows what this could be?

**Comment by antoniohof** [comment]
yes, getSpatialStructure returns objects with type: null.
as well as getIfcType.

I use it to label the IFC parts if they don't have a name.
