### ISSUE TITLE
The windows are not transparent

### ISSUE THREAD

**Issue by SpiderProjectDeveloper** [IFCjs/web-ifc-three#69]
Hello!
I have a free ifc model (http://openifcmodel.cs.auckland.ac.nz/_models/231110AC11-Institute-Var-2-IFC.ifc)
When displayed with web-ifc-three there is a problem with the windows - these are not transparent 
![image](https://user-images.githubusercontent.com/79970639/142896648-ab35d538-ad44-4787-bee0-805fb0e22092.png)
As well I have some warnings in the developer's console (please, see the picture).

Thank you in advace!

**Comment by agviegas** [comment]
Hi, the windows are opaque because by default web-ifc-three loads the `IfcSpaces` in the model. You can disable them like this:

```js
import { IFCSPACE, IFCOPENINGELEMENT } from 'web-ifc';

await this.ifcLoader.ifcManager.parser.setupOptionalCategories({
      [IFCSPACE]: false,
      [IFCOPENINGELEMENT]: false
});
```
