### ISSUE TITLE
Split model by his layers

### ISSUE THREAD

**Issue by tomerel22** [IFCjs/web-ifc-three#70]
Is it possible to spit a IFC file by his layers?
 For example, if I have a model of house, I want to see the house without the roof and then without his last floor .

**Comment by agviegas** [comment]
Hi! You can create a subset with a given array of IDs. This means you can create multiple subsets by different "layers" of the model (e.g. floor plans, cathegory, etc). 

You can learn more about subsets [here](https://ifcjs.github.io/info/docs/Guide/web-ifc-three/Tutorials/Highlighting). To get the IDs of what you call "layers" you can check out [this tutorial](https://ifcjs.github.io/info/docs/Guide/web-ifc-three/Tutorials/Properties), where we show how to traverse the IFC model. 

We are making many tutorials right now and will release them soon. In the meantime, if you have any question about how to achieve something specific, let us know here or in the open Discord channel (this is usually faster)!
