### ISSUE TITLE
IFC with no materials fails to load

### ISSUE THREAD

**Issue by simon-gd** [IFCjs/web-ifc-three#71]
A simple IFC file that doesn't have properties or materials doesn't load. Since it seems to open fine in BIM Vision, I assume that the IFC is ok, but not 100% sure. Might be worth investigation
<img width="1587" alt="Screenshot 2021-11-30 09 51 34" src="https://user-images.githubusercontent.com/57882634/144072114-e88a1d22-3707-4873-803c-0628e89ab81d.png">

This zip contains two version of the model, the original (slightly larger) and a smaller one that was run through  Solibri IFC Optimizer (I was hoping that would fix any IFC issues the file might have, but it didn't)

[very_simple.zip](https://github.com/IFCjs/web-ifc-three/files/7626715/very_simple.zip)

.

**Comment by agviegas** [comment]
Hi! I checked this out and the error is coming from [web-ifc](https://github.com/tomvandig/web-ifc). Would you mind opening the issue there? Thanks a lot!
