### ISSUE TITLE
Strange behavior for materials rendering

### ISSUE THREAD

**Issue by thmax** [IFCjs/web-ifc-three#72]
Hey !
I'm having an issue with the materials when i use the ifcLoader from web-ifc-three.
On the first photo, you can see some materials'color is white (i also trie with the viewer and it looks the same).
If I load the same model on Trimble, the materials are fine (second photo).

![image](https://user-images.githubusercontent.com/52961165/144853955-9b428380-5466-4531-88d4-6ae4e694897f.png)
![image](https://user-images.githubusercontent.com/52961165/144854082-a89cb70f-42b6-403f-ab1d-c6535b95f00d.png)

Here's the ifc file.
[Maquette BETA-B.zip](https://github.com/IFCjs/web-ifc-three/files/7660978/Maquette.BETA-B.zip)

**Comment by agviegas** [comment]
Hi, you are correct. This error is coming from [web-ifc](https://github.com/tomvandig/web-ifc). Would you mind creating the issue there? Thank you a lot!
