### ISSUE TITLE
Incorrect processing of IfcFlowSegment elements

### ISSUE THREAD

**Issue by aybond** [IFCjs/web-ifc-three#73]
Hello there!

I`ve discovered that the last version of this example app has failed to load correctly the IFC2x3 model containing IfcFlowSegment type elements and not only:
![incorrect_december_10](https://user-images.githubusercontent.com/6682452/145554253-4fd8b25b-eb62-4fd7-b119-abf5022a5dfc.png)

The previously pulled version (November 22 2021) loads the segment elements correctly:
![correct_november_22](https://user-images.githubusercontent.com/6682452/145554230-23db179c-44b2-4ef9-b50e-eb89772cdaf8.png)

The link for the test IFC2x3 model: 
https://drive.google.com/file/d/1SqFwiIRAWSlvaTPQll_ArCZ_kEYrX02z/view?usp=sharing

**Comment by aybond** [comment]
Hello there again!

Library versions for which the model is loaded integrally:
- three: **0.132.2**
- web-ifc: **0.0.28**
- web-ifc-viewer: **1.0.103**

**Comment by agviegas** [comment]
Hi! I think this is fixed in the latest versions:
![image](https://user-images.githubusercontent.com/56475338/150433914-12b70d21-8331-40c8-a2cc-d4b1b5713c1a.png)
