### ISSUE TITLE
Object absolute placement

### ISSUE THREAD

**Issue by josesoutoleon** [IFCjs/web-ifc-three#74]
Actually is pissible to get object placement coordinates wich are relative to other object, parent object. 
Some times is very useful to know what is the absolute object placment referred to project placement coordinates.

So please add an absolute object placement property to objects in order to get it.

A more generic implementation woul be to get absolute placement not only referred to project placement, also get the absolute placement related to another object.

For me getting object absolute placment refered to project placment is good enough.

Thank you.

**Comment by agviegas** [comment]
Hey, would you mind bringing this to [web-ifc](https://github.com/tomvandig/web-ifc)?

**Comment by josesoutoleon** [comment]
I close this issue beacause it has been moved to ticket 116 in web-ifc project
