### ISSUE TITLE
How to setWasmPath with react-three-fiber?

### ISSUE THREAD

**Issue by msageryd** [IFCjs/web-ifc-three#75]
I'm not able to load my ifc model. Have tried to copy `web-ifc.wasm` to the project root. Also tried to set the path to various places. But I don't really know where "I am" in the folder tree to be able to set a relative path.

Q1. Is the below the correct approach to configure the loader when I don't have access to it imperatively, as in regular Three?

Q2. What should I set the path to?

```
import {IFCLoader} from 'three/examples/jsm/loaders/IFCLoader';
import {useLoader} from '@react-three/fiber';

...

const Model = () => {
  const model = useLoader(IFCLoader, '/test.ifc', (loader) => {
    loader.ifcManager.setWasmPath('??');
  });

  return (
    <Suspense fallback={null}>
      <primitive object={model.scene} />
    </Suspense>
  );
};
```

**Comment by agviegas** [comment]
Hi! I recommend you using our repositories, as the library is quite young and the update rate is much faster than the updates to three.js. You can import `web-ifc-three` and work with that.

I have no experience with react-three-fiber, but you have to place the WASM files in the folder where the static files are. I think react has a `public` folder containing that, doesn't it?

**Comment by Amar-Gill** [comment]
React will start looking from project root. I put my wasm files in a `resources/` folder, so I have `manager.setWasmPath('resources/');`

**Comment by agviegas** [comment]
Hey, this should be solved following the given pointers. If not, let us know!

**Comment by amapic** [comment]
Hi,
Can you show your final code ? I am having hard time trying to do this with fiber.
Thanks

**Comment by Amar-Gill** [comment]
Does this help: https://github.com/Amar-Gill/vite-r3f-ifcjs-hello-world/tree/main

**Comment by amapic** [comment]
Thank you
