### ISSUE TITLE
RangeError: Maximum call stack size exceeded - when creating subsets

### ISSUE THREAD

**Issue by beachtom** [IFCjs/web-ifc-three#76]
Hi,

When creating a very large subset I get the following error:

IFCLoader.js?8ae8:478 Uncaught RangeError: Maximum call stack size exceeded
    at SubsetCreator.insertIndicesAtGroup (IFCLoader.js?8ae8:478)

This is at this line;

 this.tempIndex.splice(position, 0, ...(indicesByGroup.slice(offset, offset + batchSize)));
      

My initial thought was the variable spread operator is causing the issue - but it looks like some attempted fix has already been in place. My only thought is that the batch size must be reduced further - but really not sure what this is happening.

**Comment by agviegas** [comment]
Solved in 0.0.98. Let us know if this happens again!
