### ISSUE TITLE
Issue when creating subsets with webworkers in production

### ISSUE THREAD

**Issue by favreau84** [IFCjs/web-ifc-three#77]
web-ifc-three: 0.0.96

## Description

I'm trying to create a subset from every expressIDs of one model. The subset creation ends with this error : 

<img width="432" alt="error" src="https://user-images.githubusercontent.com/18169247/146736293-708a23aa-c427-4e2d-ba92-c9518529ac47.png">

## Detail

- It does not fail for every files : File A (OK), File B (KO).
- It does not fail in localhost, but in production.
-  [File A](https://github.com/IFCjs/web-ifc-three/files/7743707/gourreau.ifc.zip)
- [File B](https://github.com/IFCjs/web-ifc-three/files/7743714/CATA_L1.ifc.zip)

![Screenshot 2021-12-20 at 09 22 48](https://user-images.githubusercontent.com/18169247/146735963-a877e0d4-30fb-4c78-99e7-04be1ba07a08.png)

## Notes

- Related to the number of elements of model (file B) ?
- Related to the structure of the  ifc model (file B) ? (from a structural model in Tekla)

**Comment by favreau84** [comment]
Here another example of file B (KO) that ends with this error :
[HANDRAIL.ifc.zip](https://github.com/IFCjs/web-ifc-three/files/7743920/HANDRAIL.ifc.zip)


![image](https://user-images.githubusercontent.com/18169247/146739922-c361722c-f51d-45c8-9119-4230338cb61d.png)

**Comment by dlabz** [comment]
you could add a runtime param to increase node stack and see if that helps:

`node --stack-size=65500 app.js`

**Comment by favreau84** [comment]
@dlabz , @agviegas , increasing the stack size to 65500 still results with the same error for both files : 
![image](https://user-images.githubusercontent.com/18169247/146752189-60a95d5e-615c-4703-9c1e-266ea346600a.png)

It seems that the error occurs for models with lots of expressIDs ...

**Comment by agviegas** [comment]
Hi, I think I fixed this in the last versions. Can you please confirm it?

**Comment by favreau84** [comment]
Hi @agviegas , yes, you did fix it. I close the issue. Thanks.
