### ISSUE TITLE
Window openings sometimes don't work

### ISSUE THREAD

**Issue by dasviridov** [IFCjs/web-ifc-three#78]
Loading some of ifc models for houses result models being loaded without window openings. See screenshots of source ifc file in BIM Viewer and the same file in web-ifc-viewer. Source file is attached as well.

![web-ifc-viewer](https://user-images.githubusercontent.com/15569157/147401341-38508e98-6043-460f-95ab-d0d50e7a2ae7.png)

![bim_vision](https://user-images.githubusercontent.com/15569157/147401350-67d3c869-d356-405b-a7c6-5bce3772b79f.png)

Some models I have, do load correctly. Others may have no window openings on ground floor but have openings on first floor.

Happy to help with testing.

web-ifc-three: 0.0.99

model: [model.zip](https://github.com/IFCjs/web-ifc-three/files/7776648/model.zip)

**Comment by agviegas** [comment]
Hi! It looks like an issue with boolean operations. Can you please create this issue in [web-ifc](https://github.com/tomvandig/web-ifc)? This is where we handle geometric problem. Thanks a lot!
