### ISSUE TITLE
Incorrect Rendering 

### ISSUE THREAD

**Issue by simon-gd** [IFCjs/web-ifc-three#79]
Attaching a screenshots and IFC model of a example Solibri buildings that web-ifc-three seems to have trouble with.

![web-ifc-three](https://user-images.githubusercontent.com/57882634/147614593-6c94f96d-8571-4920-ad6c-5d74fc7c271d.png)

![Same model in BIM Vision](https://user-images.githubusercontent.com/57882634/147614596-902d637e-f195-471a-820b-b016e5f54883.png)

[Solibri Building.zip](https://github.com/IFCjs/web-ifc-three/files/7786715/Solibri.Building.zip)
.

**Comment by agviegas** [comment]
Hi! Can you please create this issue in [web-ifc](https://github.com/tomvandig/web-ifc)? This is where we handle geometric problem. Thanks a lot!
