### ISSUE TITLE
Remove GetLine function from webworkers

### ISSUE THREAD

**Issue by favreau84** [IFCjs/web-ifc-three#82]
# Problem
(related to https://github.com/tomvandig/web-ifc/issues/138)

I'm using the ifcAPI.GetLine method in the context of web-ifc-three + webworkers = true  in ordre to modify later on the ifc file.
The problem is that in this context, the output is not "typed" correctly: the webworker drops the typing and we are losing the ToTape method of the prototype.
This is a problem because I can't use the WriteLine method on the modified object...

![image](https://user-images.githubusercontent.com/18169247/151626743-2eb2c061-7669-42fb-a9db-b9ac92af0c41.png)

# Solution

what @tomvandig suggests : "Remove GetLine function from webworkers"...

# Context

https://discord.com/channels/799990228336115742/799990228336115745/935220928596541460

![image](https://user-images.githubusercontent.com/18169247/151626351-9fb80a74-38cf-402e-a160-5d3fb0270477.png)

**Comment by agviegas** [comment]
Hey, I think this is related to [this other issue](https://github.com/IFCjs/web-ifc-three/issues/59). Perhaps instead of removing the method we can find a way to reconstruct the typing after the serialization. What do you think?

**Comment by favreau84** [comment]
Hi @agviegas , I was about to release a new version of CAPLA that enables architects / BIM manager to modify the position of one ifc site when it is not compliant with the project origin. 

It will be a first great example on how editing .ifc with ifc.js (the ifc position in this case) can simplify some BIM processes.

There's still this issue though... And I don't want to remove webworkers since it provides a great experience at load time. Any quick win. ?

Reminder : I've got this error when trying to writeLine.
<img width="1365" alt="error" src="https://user-images.githubusercontent.com/18169247/163390519-c2c9db79-eba8-4f4c-bbaf-2f9c905d36f6.png">

**Comment by agviegas** [comment]
Fixed from `0.0.113`. I will publish this on sunday, I hope it's not too late 😉

**Comment by favreau84** [comment]
Great !
