### ISSUE TITLE
getSpatialStructure Failed

### ISSUE THREAD

**Issue by lewibs** [IFCjs/web-ifc-three#94]
spatial structure failed to generate as shown in the attached image.
https://photos.app.goo.gl/so4mRnKGY5pMge748

Here is the file that was used for this error.
https://drive.google.com/file/d/1UFl0hz8nkoh_-oDxJ_xZxa6fc24mm3KB/view?usp=sharing

The IFC loads mostly successfully missing a few components this may have been the cause of the issue. This is possibly related to this issue with more context given there:
https://github.com/tomvandig/web-ifc/issues/152

**Comment by aka-blackboots** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @aka-blackboots! Thanks for taking this bounty! The due date is December 19, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by aka-blackboots** [comment]
::take

**Comment by aka-blackboots** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @aka-blackboots! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @aka-blackboots! Thanks for taking this bounty! The due date is December 19, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by aka-blackboots** [comment]
::drop

**Comment by antoniohof** [comment]
this is fixed in the last version 
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/8311230/217949637-9f6d8d74-8ef0-4e8e-8964-04a637d94c83.png">
