### ISSUE TITLE
Geometry doesn't render correctly when using web workers

### ISSUE THREAD

**Issue by MadsHolten** [IFCjs/web-ifc-three#97]
When using web workers some geometries don't render as they should. (web-ifc-three@0.0.108, web-ifc@0.0.33).

![webworkers](https://user-images.githubusercontent.com/13613073/161492792-e67d4869-5a03-43ce-a89d-5a62dff8ee99.png).

If an object is picked (and a subset of the geometry is generated) the object occurs fully as it should.

Reproduce:
[Without web workers](https://ld-bim.web.app/?duplex=true&useWorkers=false)
[With web workers](https://ld-bim.web.app/?duplex=true&useWorkers=true)

**Comment by agviegas** [comment]
I forgot to apply `side: DoubleSide` to the materials during the de-serialization progress. I've fixed, this, will be published from `0.0.113`.
