### ISSUE TITLE
No basis found for brep!  

### ISSUE THREAD

**Issue by fabriceblache** [IFCjs/web-ifc-three#98]
Hello

I have this problème in the console when I open an IFC. There nothing on the screen

"No basis found for brep!            bundle.js:38451 
zero triNo basis found for brep!
"
...
, put_char: function(tty, val) {
          if (val === null || val === 10) {
->            out(UTF8ArrayToString(tty.output, 0));
            tty.output = [];
          } else {
            if (val != 0)
              tty.output.push(val);
          }
...

Best regards,
Fabrice

**Comment by agviegas** [comment]
Hi, we need to see your code and/or the IFC file that you are using.
